name: nash_sever
description: A new Flutter project.

version: 1.0.1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_route: ^7.8.4
  webview_flutter: ^4.5.0
  flutter_inappwebview: ^5.8.0

  get_it: ^7.6.7
  injectable: ^2.1.1
  flutter_bloc: ^8.1.3
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  injectable_generator: ^2.1.5
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/app_icon.png"
  adaptive_icon_foreground: "assets/app_icon/app_icon.png"
  adaptive_icon_background: null

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
